language: c
compiler: gcc
dist: trusty
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common gobject-introspection libwebkit2gtk-4.0-dev build-essential valac cmake glib2.0 gtk+3.0 gstreamer1.0 libjson-glib-dev libsoup2.4
script:
  - ./autogen.sh
  - make
