language: c
compiler: gcc
before_install:
  - sudo add-apt-repository ppa:vala-team/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq gnome-common libglib2.0-dev libgtk-3-dev
         gobject-introspection glib-2.0 gtk+-3.0 gstreamer-1.0 json-glib-1.0
         gio-2.0 webkit2gtk-4.0 libsoup-2.4
         
script:
  - ./autogen.sh
  - make
