
name: gradio
version: 5.9.0
summary: P A GTK3 app for finding and listening to internet radio stations 
description: |
  Search and find radio stations, listen to them, and this 
  without needing to use a browser or enter an internet radio stream URL.
  
  Gradio uses the community-based ‘Radio Browser‘ website for its database 
  backend. 

grade: devel
confinement: devmode
